# Generated by Django 5.1.7 on 2025-05-15 02:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_respuestafinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
        ),
    ]
